services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      JAVA_OPTS: -Xmx512m
      AMADEUS_API_KEY: ${AMADEUS_API_KEY}
      AMADEUS_API_SECRET: ${AMADEUS_API_SECRET}
    command: ["java", "-jar", "app.jar"]
